import Head from 'next/head';
import HeroSection from '@/components/hero-section';
import MapSection from '@/components/map-section';
import NavBar from '@/components/navbar';
import SwitchSection from '@/components/switch-section';
import Features from '@/components/features';
import Testimonials from '@/components/testimonials';
import Footer from '@/components/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Personarise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <NavBar />
        <HeroSection />
        <MapSection />
        <SwitchSection />
        <Features />
        <Testimonials />
      </main>
      <Footer />
    </>
  );
}
